# Generated by Django 3.0.7 on 2020-06-22 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Todos', '0002_todoitem_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todoitem',
            name='timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
