# Generated by Django 3.0.7 on 2020-06-22 22:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Todos', '0003_auto_20200623_0651'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todoitem',
            name='timestamp',
        ),
    ]
