# Generated by Django 3.0.7 on 2020-06-22 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Todos', '0004_remove_todoitem_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='todoitem',
            name='comment',
            field=models.TextField(default=2),
            preserve_default=False,
        ),
    ]
