# Generated by Django 3.0.7 on 2020-06-23 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Todos', '0005_todoitem_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todoitem',
            name='comment',
        ),
        migrations.AddField(
            model_name='todoitem',
            name='entry_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
