# Generated by Django 3.0.7 on 2020-06-23 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Todos', '0007_todoitem_timestamp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todoitem',
            name='entry_date',
        ),
        migrations.AddField(
            model_name='todoitem',
            name='target_timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
