# Generated by Django 3.0.7 on 2020-06-23 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Todos', '0008_auto_20200624_0432'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todoitem',
            name='target_timestamp',
            field=models.DateTimeField(),
        ),
    ]
